name: sample-angular
services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: ddiebel/sample-angular
    name: sample-angular
